apiVersion: apps/v1
kind: Deployment
metadata:
  name: hapidemo2
  labels:
    app: hapidemo2
spec:
  replicas: 0
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: hapidemo1
        image: hapidemo1
        ports:
        - containerPort: 8097